{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "570aa3e9-9fba-47c1-9514-eee113f7ab05",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Estimate cell volume based on Beauvoit et al\n",
    "def estimateVcell(T):\n",
    "    import math\n",
    "    Vcell = ((0.02894333/(0.00760074+(math.e**(-0.18324543*T))))-0.03277816)*(10**-12) # units = m3\n",
    "    return Vcell\n",
    "\n",
    "#Estimate pericarp volume based on Jose's data\n",
    "def estimateVpericarp(T,hollow=False):\n",
    "    #assuming sphere\n",
    "    Vpericarp = (0.0000889527 +((0.000003593996 - 0.0000889527)/(1 +((T/28.56023)**9.692893)))) # units = m3\n",
    "    #\n",
    "    if hollow:\n",
    "        #assuming hollowsphere - 20%\n",
    "        Vpericarp = (0.0000007121165 +((0.00000002819613 - 7.121165e-7)/(1 +((T/28.55635)**9.567273)))) # units = m3\n",
    "    return Vpericarp\n",
    "\n",
    "#Estimate number of cells\n",
    "def estimateNcell(T,hollow=False):\n",
    "    Vcell = estimateVcell(T)\t\t\t\t#unit = m3\n",
    "    Vpericarp = estimateVpericarp(T,hollow)\t#unit = m3\n",
    "    return Vpericarp/Vcell\n",
    "\n",
    "#Estimate volume of cell wall in a cell\n",
    "def estimateVcellwall(T):\n",
    "    Vcell = estimateVcell(T)\t\t\t#unit = m3\n",
    "    a = Vcell**(1.0/3)\n",
    "    #cell wall thickness = 100 nm according to figure 19-68, https://www.ncbi.nlm.nih.gov/books/NBK26928/\n",
    "    b=100*(10**-9)\t\t\t\t#unit = m\n",
    "    y = (8*(b**3))+(6*(a**2)*b)-(12*a*(b**2))\n",
    "    return y\n",
    "\n",
    "\n",
    "#Estimate volume of cell wall\n",
    "def estimateTotalVcellwall(T,Ncell=0,hollow=False):\n",
    "    Vcellwall = estimateVcellwall(T)\t\t#unit = m3\n",
    "    if Ncell == 0:\n",
    "        Ncell = estimateNcell(T,hollow)\n",
    "    return Vcellwall*Ncell\t\t\t#unit = m3/fruit\n",
    "\n",
    "#Esimate cellulose content\n",
    "def celluloseLevels(T,Ncells=0,hollow=False):\n",
    "    p_cellulose = 1.54*(10**6)              # unit = g/m3\n",
    "    x = estimateTotalVcellwall(T,Ncells,hollow)    # unit = m3/fruit\n",
    "    y = x*p_cellulose                       # unit = g/fruit\n",
    "    z = (y/180.16) * 1000                   # unit = mmol/fruit\n",
    "    return z\n",
    "\n",
    "\n",
    "#Estimate cellulose demand flux\n",
    "def celluloseDemandFlux(t,Ncells=0,unit_time=1):\n",
    "    z = celluloseLevels(t,Ncells)-celluloseLevels(t-unit_time,Ncells)\t#unit = mmol/fruit/unit_time\n",
    "    return z\n",
    "\n",
    "#Estimate cell membrane of a cell\n",
    "def estimateVcellmembrane(T):\n",
    "    Vcell = estimateVcell(T)\n",
    "    a=Vcell**(1.0/3)\n",
    "    #cell wall thickness = 100 nm according to figure 19-68, https://www.ncbi.nlm.nih.gov/books/NBK26928/\n",
    "    b=100*(10**-9)\n",
    "    #cell membrane thickness = 10 nm according to https://hypertextbook.com/facts/2001/JenniferShloming.shtml (see Hine, Robert. \"Membrane.\" The Facts on File Dictionary of Biology. 3rd ed. New York: Checkmark, 1999: 198.)\n",
    "    #c = 10*(10**-9)\t\t\t\t#unit = m\n",
    "    #cell membrane thickness = 4 nm BioNumbers\n",
    "    c = 4*(10**-9)\t\t\t\t#unit = m\n",
    "    y = (8*(c**3))+(6*(a**2)*c)+(24*(b**2)*c)-(12*(c**2)*(a-(2*b)))-(24*a*b*c)\t#unit = m3\n",
    "    return y\n",
    "\n",
    "#Estimate total volume of cell membrane\n",
    "def estimateTotalVcellmembrane(T,Ncell=0,hollow=False):\n",
    "    Vcellmembrane = estimateVcellmembrane(T)\t\t#unit = m3\n",
    "    if Ncell == 0:\n",
    "        Ncell = estimateNcell(T,hollow)\n",
    "    return Vcellmembrane*Ncell\t\t\t#unit = m3/fruit\n",
    "\n",
    "#Esimate phospholipid content\n",
    "def phospholipidLevels(T,Ncells=0,scaling_factor=1):\n",
    "    p_phospholipid = 0.975*(10**6)              \t# unit = g/m3\n",
    "    x = estimateTotalVcellmembrane(T,Ncells)    \t# unit = m3/fruit\n",
    "    y = x*p_phospholipid                       \t\t# unit = g/fruit\n",
    "    z = (y/689.978637415773) * 1000 * scaling_factor\t# unit = mmol/fruit\n",
    "    return z\n",
    "\n",
    "#Estimate phospholipid demand flux\n",
    "def phospholipidDemandFlux(t,Ncells=0,unit_time=1,scaling_factor=1):\n",
    "    z = phospholipidLevels(t,Ncells,scaling_factor)-phospholipidLevels(t-unit_time,Ncells,scaling_factor)\t#unit = mmol/fruit/unit_time\n",
    "    return z\n",
    "\n",
    "\n",
    "#Estimate total cytosolic volume\n",
    "def estimateVcyt(T,Ncell=0,hollow=False):\n",
    "    import math\n",
    "    j = T*24*60\n",
    "    Vvac = 0.853*(1-math.e**(float(-2292-j)/10633))\n",
    "    Vcyt = (0.933-Vvac)/1.13\n",
    "    if Ncell == 0:\n",
    "        Ncell = estimateNcell(T,hollow)\n",
    "    return Vcyt*estimateVcell(T)*Ncell\n",
    "\n",
    "#Estimate total protein content\n",
    "def estimateProteinContent(T,Ncell=0,ProtConc=21458.1747597,hollow=False):\n",
    "    if Ncell == 0:\n",
    "        Ncell = estimateNcell(T,hollow)\n",
    "    Vcyt = estimateVcyt(T,Ncell,hollow)\t\t# unit = m3/fruit\n",
    "    #ProtConc#                                  # unit = mmol/m3\n",
    "    return ProtConc*Vcyt                        # unit = mmol/fruit\n",
    "\n",
    "#Estimate Protein demand\n",
    "def estimateProteinDemandFlux(T,Ncell=0,ProtConc=21458.1747597,unit_time=1,hollow=False):\n",
    "    if Ncell == 0:\n",
    "        Ncell = estimateNcell(T,hollow)\n",
    "    z = estimateProteinContent(T,Ncell,ProtConc=21458.1747597) - estimateProteinContent(T-unit_time,Ncell,ProtConc=21458.1747597)\t# unit = mmol/fruit/unit_time\n",
    "    return z"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
